config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: redirect('/dayLog/list')
  resources :memos
   
  post 'dayLog/list', to: 'memos#list', as: 'list'
  get 'dayLog/memos/mark_ready', to: 'memos#mark_ready'

  get 'dayLog/memos/reopen', to: 'memos#reopen'
  get 'dayLog/memos/delete', to: 'memos#delete'
  get 'dayLog/memos/delete_recurrence', to: 'memos#delete_recurrence'

  get '/redirect', to: 'memos#redirect', as: 'redirect'
  get '/callback', to: 'memos#callback', as: 'callback'
  get '/calendars', to: 'memos#calendars', as: 'calendars'
  # post '/events/:calendar_id', to: 'memos#new_event', as: 'new_event', calendar_id: /[^\/]+/
    post '/new_event', to: 'memos#new_event', as: 'new_event', calendar_id: /[^\/]+/

  get 'dayLog/list', to: 'memos#list'
  post 'memos/new', to: 'memos#create'

  get 'memos/new'
  post 'memos/create'
  patch 'memos/update'
  get 'memos/show'
  get 'memos/edit'
  get 'memos/delete'
  get 'memos/delete_recurrence'
  get 'memos/update'
  get 'memos/show_subjects'
  get 'memos/mark_ready'
  get 'memos/reopen'


end

app/models/memo.rb
class Memo < ApplicationRecord
	validates_presence_of :description
	belongs_to :room
	attr_accessor :start_date
	attr_accessor :end_date
	attr_accessor :recurrence
	attr_accessor :pattern
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
   	
    protect_from_forgery with: :null_session
    before_action :authenticate_user!

   include MemoHelper       
   $stored_date = nil

    def redirect
      client = Signet::OAuth2::Client.new({
        client_id: Rails.application.secrets.google_client_id,
        client_secret: Rails.application.secrets.google_client_secret,
        authorization_uri: 'https://accounts.google.com/o/oauth2/auth',
        scope: Google::Apis::CalendarV3::AUTH_CALENDAR,
        redirect_uri: callback_url
      })
      puts "params ------------------------"
      puts params[:date]
      $stored_date = params[:date]
      puts "params ------------------------"

      redirect_to client.authorization_uri.to_s
    end

    def callback
      client = Signet::OAuth2::Client.new({
        client_id: Rails.application.secrets.google_client_id,
        client_secret: Rails.application.secrets.google_client_secret,
        token_credential_uri: 'https://accounts.google.com/o/oauth2/token',
        redirect_uri: callback_url,
        code: params[:code]
      })

      response = client.fetch_access_token!

      session[:authorization] = response

      redirect_to calendars_url
    end

    def calendars
      client = Signet::OAuth2::Client.new({
        client_id: Rails.application.secrets.google_client_id,
        client_secret: Rails.application.secrets.google_client_secret,
        token_credential_uri: 'https://accounts.google.com/o/oauth2/token'
      })

      client.update!(session[:authorization])

      service = Google::Apis::CalendarV3::CalendarService.new
      service.authorization = client

      @calendar_list = service.list_calendar_lists

      
    end

     def new_event
      client = Signet::OAuth2::Client.new({
        client_id: Rails.application.secrets.google_client_id,
        client_secret: Rails.application.secrets.google_client_secret,
        token_credential_uri: 'https://accounts.google.com/o/oauth2/token'
      })

      client.update!(session[:authorization])

      service = Google::Apis::CalendarV3::CalendarService.new
      service.authorization = client

      puts "@stored_date ------------------------"
      puts $stored_date
      puts "@stored_date ------------------------"
      date = Date.strptime($stored_date, "%Y-%m-%d")

      @memos = Memo.where('deadline BETWEEN ? AND ?', date.beginning_of_day, date.end_of_day).all
      @memos.each do |memo|
        event = Google::Apis::CalendarV3::Event.new({
          start: Google::Apis::CalendarV3::EventDateTime.new(date: date),
          end: Google::Apis::CalendarV3::EventDateTime.new(date: date + 1),
          summary: memo.description
        })
        service.insert_event(params[:calendar_id], event)
      end

      # event = Google::Apis::CalendarV3::Event.new({
      #   start: Google::Apis::CalendarV3::EventDateTime.new(date: date),
      #   end: Google::Apis::CalendarV3::EventDateTime.new(date: date + 1),
      #   summary: 'New event!'
      # })

      # puts "event"
      # puts event
      # puts event.start
      # puts event.end
      # puts "------------------------"

      # service.insert_event(params[:calendar_id], event)

      redirect_to list_url
    end

   	def list
      if params[:date].blank?
        @date = Date.current();

      else
        @date = Date.strptime(params[:date], "%Y-%m-%d")
      end
      @memos = Memo.where('deadline BETWEEN ? AND ?', @date.beginning_of_day, @date.end_of_day).all

      @stored_date = @date
      @done = 0
      @not_done = 0

      @memos.each do |m|
        m.is_done ? @done+=1 : @not_done+=1
      end
   	end

    def mark_ready
      @memo = Memo.find(params[:id])
      @memo.update_attribute(:is_done, true)
      @memo.update_attribute(:deadline, Date.today)
      @memo.is_done = true
      render :nothing => true
      # redirect_to :action => 'list'
    end

    def reopen
      @memo = Memo.find(params[:id])
      @memo.update_attribute(:is_done, false)
      @memo.update_attribute(:deadline, nil)
      @memo.is_done = false
      render :nothing => true
      # redirect_to :action => 'list'
    end

   	def list_open																																						
   		@memos = Memo.where("is_done = ?", true)
   	end

   	def list_ready
   		@memos = Memo.where("is_done = ?", false)
   	end
   
   	def show
   		@memo = Memo.find(params[:id])
   	end
   
   	def new

   	end

 	def create
    @room = Room.where("room_id = ?", memo_params[:room_id]).first

      @date = DateTime.strptime(params[:memo]["deadline"], '%Y-%m-%d').change({ hour: params[:memo]["deadline(4i)"].to_i, min: params[:memo]["deadline(5i)"].to_i})  
      @memo = @room.memos.create(room_id: memo_params[:room_id], description: memo_params[:description], deadline: @date, deadline: memo_params[:deadline], is_done: memo_params[:is_done], is_recurring: false )
      redirect_back(fallback_location: root_path)
  end
   
	def memo_params
   		params.require(:memo).permit(:room_id, :description, :deadline, :deadline, :memo_time, :time_stamp, :is_done, :is_recurring, :start_date, :end_date, :recurrence, :pattern)
	end

 	def edit
    @c = Memo.find(params[:id])
  end
   
 	def update
    @memo = Memo.find(params[:id])
    @memo.update_attributes(memo_params)
    redirect_back(fallback_location: root_path)
  end

 	def memo_param
 		params.require(:memo).permit(:room_no, :description, :deadline)
	end
   
 	def delete
 		Memo.find(params[:id]).destroy
 		redirect_to :back
 	end

  def delete_recurrence
    Memo.where(:event_id => params[:event_id]).destroy_all
    redirect_to :back
  end

 	def show_rooms
 		@room = Room.find(params[:id])
	end											

end

app/helpers/memo_helper.rb
module MemoHelper
	
end

app/views/memos/_edit.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">

    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Edytuj Memo</h4>
    </div>

    <div class="modal-body">
      <%= bootstrap_form_for @c, remote: true, html: { style: "display:inline;" } do |f| %>
        <%= f.text_field :description, label: "Opis" %>
        <%= f.collection_select :room_id, Room.all, :room_id, :room_id, label: "Pokój" %>  
        <%= f.date_select :deadline, label: "Data Wykonania"%>
        <%= f.time_select :deadline, :ignore_date => true %>
        <%= f.hidden_field :time_stamp, :value => Date.today %>

        <div class="modal-footer">
          <div class="text-right">
              <a href="" data-dismiss="modal" class="btn btn-default">Anuluj</a>
              <%= f.submit "Uaktualnij", :class => 'btn btn-primary' %>
          </div>
        </div>
        
      <% end %>
    </div>

  </div>
</div>

app/views/memos/_new.html.erb
x<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title">Utwórz Memo</h4>
        </div>

        <div class="modal-body">
            <%= bootstrap_form_for :memo, remote: true, html: { style: "display:inline;" } do |f| %>

                <!-- Room ID & Time Picker -->
                <div class="row">
                    <div class="col-xs-6">    
                        <%= f.collection_select :room_id, Room.all, :room_id, :room_id, label: "Pokój" %>
                    </div>

                    <div class="col-xs-6">
                        <%= f.time_select :deadline, label: "Godzina", :ignore_date => true %>
                    </div>
                </div>

                <!-- Description -->
                <div class="row">
                    <div class="col-xs-12">          
                        <%= f.text_field :description, label: "Opis" %>
                    </div>
                </div>

                <!-- Date Picker -->
                <div class="row" id="new_memo_date_field">
                    <div class="col-xs-6 form-group">
                        <div class="btn-group">
                            <label>Data wykonania</label>
                            <div class="input-group date" data-provide='datepicker'>
                                <%= f.text_field :deadline, class: 'form-control' , :value => Date.today(), 
                                    hide_label: true  %>
                                <span class="input-group-addon">
                                <i class="fa fa-calendar"></i>
                            </span>
                            </div>
                        </div>
                    </div>
                </div>

                <%= f.hidden_field :time_stamp, :value => Date.today %>
                <%= f.hidden_field :is_done, :value => false %>

                <!-- Footer -->
                <div class="modal-footer">
                    <div class="text-right">
                        <a href="" data-dismiss="modal" class="btn btn-default">Anuluj</a>
                        <%= f.submit "Utwórz", :class => 'btn btn-primary' %>
                    </div>
                </div>

            <% end %>

        </div>        

    </div>
</div

app/views/memos/calendars.html.erb
<!-- <div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title">Kalendarze</h4>
        </div>

        <div class="modal-body">
            <table class="g-table-card g-table-issues" >
                <thead>
                    <tr>
                        <th> summary</th>
                        <th> id </th>
                    </tr>
                </thead>

                <tbody>
                    <% @calendar_list.items.each do |calendar| %>
                        <tr> 
                            <td> <%= calendar.summary %> </td>
                            <td> <%= calendar.id %> </td>
                        </tr>
                    <% end %>
                
                </tbody>
                
            </table>

        </div>        

        <div class="modal-footer">
            <div class="text-right">
                <a href="" data-dismiss="modal" class="btn btn-default">Anuluj</a>
            </div>
        </div>
    </div>
</div> -->


<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>MEMOS</title>
    </head>

    <body>
        <!-- Fluid Container -->
        <!-- <div class="container-fluid g-aside-has-aside"> -->

            <!-- Header with main buttons -->
            <div class="row g-header">
                <div class="col-sm-12">

                    <!-- Screen Name -->
                    <div class="pull-left g-navigation-text g-mobile-hide">
                        <h4>Dodaj do kalendarza Google</h4>
                    </div>             

                </div>
            </div>    <!-- Sub Navigation Tabs -->
            
            
            <!-- Application Content -->
            <div class="g-application-content">    
                <!-- Card Row -->
                <div class="row">
                    <div class="col-md-12">            
                        <table class="g-table-card g-table-issues tablesorter mysortable" id="memo_table">
                            <thead>
                    <tr>
                        <th> Kalendarz</th>
                        <th> ID </th>
                        <th> Dodaj </th>
                    </tr>
                </thead>

                <tbody>
                    <% @calendar_list.items.each do |calendar| %>
                        <tr> 
                            <td> <%= calendar.summary %> </td>
                            <td> <%= calendar.id %> </td>
                            <td> 

                            <%= bootstrap_form_tag url: "/new_event" do |f| %>
                                <%= f.hidden_field :calendar_id, :value =>  calendar.id %>
                                <%= f.submit "Dodaj", :class => 'btn btn-primary' %>
                            <% end %>
                                       
                            </td>
                        </tr>
                    <% end %>
                
                </tbody>
                        </table>
                    </div>
                </div>  
                <!-- / Card Row -->
           </div>        
        <!-- </div> -->
    </body>
    <footer>
        <div class="text-right">
            <div class="btn-group">
                <%= link_to "Anuluj", list_path, :class => "btn btn-primary g-ripple-effect" %>                
            </div>
        </div>

    </footer>

</html>

app/views/memos/edit.js.erb
$("#memo-modal").html("<%= escape_javascript(render 'edit') %>")
$("#memo-modal").modal("show")

app/views/memos/list.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>MEMOS</title>
    </head>

    <body>
        <!-- Fluid Container -->
        <!-- <div class="container-fluid g-aside-has-aside"> -->

            <!-- Header with main buttons -->
            <div class="row g-header">
                <div class="col-sm-12">

                    <!-- Screen Name -->
                    <div class="pull-left g-navigation-text g-mobile-hide">
                        <h4>Dziennik</h4>
                    </div>

                    <div class="pull-right ">

                        <!-- datepicker -->
                        <div id="memo-calendar" class="btn-group" style="max-width: 140px;">
                            <div class="input-group date" data-provide='datepicker'>
                            <%= form_for :memo, :url => url_for(:action => 'list'), :html=> {:id => 'date-form'}  do |f| %>
                                <%= f.text_field :date, class: 'form-control' , :value => @stored_date %>
                            <% end %>
                                <span class="input-group-addon">
                                    <div data-icon="M" class="icon"></div>
                                </span>
                            </div>
                        </div>  
                        <script>
                            $('#memo-calendar .input-group.date').datepicker({
                                format: 'yyyy-mm-dd',
                                language: "pl",
                                autoclose: true,
                                todayHighlight: true,
                                todayBtn: "linked"
                            }).on('changeDate', function (a) {
                                // var form = document.getElementById("date-form");
                                // form.submit();
                                var date = a.date.getFullYear() + "-" + (a.date.getMonth() + 1) + "-" + a.date.getDate();
                                var link = window.location.href.split('?')[0] + "?date=" + date;
                                window.location.href = link;
                                // $.get("/dayLog/list", {date});
                            });
                        </script>

                        <!-- Primary Action Button -->
                        <div class="btn-group">
                            <%= link_to "Utwórz ", new_memo_path, remote: true, :class => "btn btn-primary g-ripple-effect" %>               
                        </div>

                        <!-- EXPORT -->

                        <div class="btn-group">
                            <%= link_to "Dodaj do kalendarza", redirect_path(:date => @stored_date), :class => "btn btn-primary g-ripple-effect" %>                
                        </div>
                    </div>                        

                </div>
            </div>    <!-- Sub Navigation Tabs -->
            
            <div class="row g-subnavigation">
                <div class="col-md-12 g-tabs">

                    <!-- All, Opened, Ready -->
                    <ul class="nav nav-pills pull-left" role="tablist">
                        <li class="showall active">   <a>Wszystkie <span class="badge g-badge-blue" id="all-number"><%= @done + @not_done -%></span></a></li>
                        <li class="showopen">  <a>Otwarte   <span class="badge g-badge-blue" id="open-number"><%= @not_done -%></span></a></li>
                        <li class="showready"> <a>Gotowe    <span class="badge g-badge-blue" id="ready-number"><%= @done -%></span></a></li>
                    </ul>  
 
                    <!-- Sortowanie --> 
                    <div class="pull-right g-mobile-hide">
                        <div class="btn-group">
                            <div class="dropdown">
                                <button class="btn btn-link dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                    Sortuj <div data-icon="T" class="icon"></div>
                                </button>
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                    <li><a id="sort_room_memo">Po pokoju</a></li>
                                    <li><a id="sort_time_memo">Po godzinie</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                            
                </div>  
            </div>
            
            <!-- Application Content -->
            <div class="g-application-content">    
                <!-- Card Row -->
                <div class="row">
                    <div class="col-md-12">            
                        <table class="g-table-card g-table-issues tablesorter mysortable" id="memo_table">
                            <thead >
                                <tr>
                                    <th> </th>  <th>Memo</th> <th>Pokój</th> <th>Data</th> <th>Godzina</th> <th></th>
                                </tr>
                            </thead>

                            <tbody>                    
                                
                                <% @memos.each do |c| %>
                                	<tr class="<%= c.is_done ? 'g-table-card-header tr-done' : 'g-table-card-header tr-not_done' =%>" >
                                        <td class="text-center g-vertical-middle g-table-card-icon-td">
                                            	<%= image_tag "Ok.png", :class => "g-issue-icon is-complete-icon-ok", :style => c.is_done ? '' : 'display: none;'%>   
                                            	<%= image_tag "Circle.png", :class => "g-issue-icon is-complete-icon-circle", :style => c.is_done ? 'display: none;' : ''%>                  
                                            </td>
                                        
                                        <td class="g-vertical-middle strike-out <%= c.is_done ? 'td-done' : '' =%>">
                                            
                                            <h4><%= c.description -%></h4>
                                        </td>                                    

                                        <td class="g-vertical-top strike-out <%= c.is_done ? 'td-done' : '' =%>">
                                            <h4><%= c.room_id -%></h4>
                                        </td>  

                                        <td class="hidden-xs hidden-sm g-vertical-top strike-out <%= c.is_done ? 'td-done' : '' =%>">
                                            <h4><%= c.deadline.strftime("%Y-%m-%d") -%></h4>
                                        </td>  

                                        <td class="hidden-xs hidden-sm g-vertical-top strike-out <%= c.is_done ? 'td-done' : '' =%>">
                                            <h4><%= c.deadline.strftime("%H:%M") -%></h4>
                                        </td>     


                                        <td class="text-right g-vertical-middle g-stay-in-one-line g-buttons-in-line"> 
                                            <div class="btn-group">
                                                <button type="button" class="btn btn-link btn-icon dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                    <div data-icon="/" class="icon"></div>
                                                </button>
                                            
                                                <ul class="dropdown-menu">
                                                    <li><%= link_to "Edytuj", edit_memo_path(c), remote: true, :class => "edit-button" , :style => c.is_done ? 'display: none;' : ''  %></li>
                                                    <li>
                                                        <%= link_to "Otwórz", "memos/reopen?id=#{c.id}", :class =>  "btn-memo-reopen reopen", remote: true  %>
                                                    <!-- <a href="#" class="btn-memo-reopen"> Re-Open </a> -->
                                                    </li>
                                                    <li>
                                                        <%= link_to "Usuń", "memos/delete?id=#{c.id}", :class =>  "btn-issues-remove"  %>
                                                    </li>
                                                    <% if c.is_recurring == true %>  
                                                    <li>
                                                        <%= link_to "Usuń serię", "memos/delete_recurrence?event_id=#{c.event_id}", :class =>  "btn-issues-remove"  %>
                                                    </li>    
                                                    <% end %>
                                                                                 
                                                    <li role="separator" class="divider"></li>
                                                    <li><a>Anuluj</a></li>
                                                </ul>
                                            </div> 
                                            <script>
                                                $(document).on('click', '.dropdown-menu', function (e) {
                                                    e.stopPropagation();
                                                });
                                            </script> 


                                            <%= button_to "Gotowe", "memos/mark_ready" , params: {id: c.id}, class: "btn btn-link btn-memo-done ready-button enabled", remote: true, method: :get, form: {style: 'display:inline-block;',  autocomplete: "off"}, :style => c.is_done ? 'display: none;' : ''%>

                                            <%= button_to "Gotowe", "", class: "btn btn-link btn-memo-done ready-button disabled", disabled: "true", form: {style: 'display:inline-block;',  autocomplete: "off"}, :style => c.is_done ? '' : 'display: none;'%>
                                        
                                        </td>                                        

                                	</tr>
               					<% end %>                   
                            </tbody>
                        </table>
                    </div>
                </div>  
                <!-- / Card Row -->
           </div>        
        <!-- </div> -->
        <div id="modal-add-memo" class="modal fade"></div>
        <div id="memo-modal" class="modal fade" ></div>
    </body>
<!-- 
    <%= javascript_include_tag "ripple-effect.js" %>
    <%= javascript_include_tag "g-aside-expand.js" %> -->

</html>

app/views/memos/new.js.erb
$("#modal-add-memo").html("<%= escape_javascript(render 'new') %>")
$("#modal-add-memo").modal("show")

$("#recurring_check_box").change(function() {
    if(this.checked)
    {
        $("#new_memo_date_field").hide()
        $("#new_memo_recurring_options").show()
        $("#new_memo_recurring_date_pickers").show()
    }
    else
    {
        $("#new_memo_date_field").show()
        $("#new_memo_recurring_options").hide()
        $("#new_memo_recurring_date_pickers").hide()         
    }
});

$("#memo_recurrence").change(function() {
    if($(this).val() == 4){
        $("#new_memo_recurring_additional").show()
    } else {
        $("#new_memo_recurring_additional").hide()
    }
});

$('#new_memo_date_field .input-group.date').datepicker({
    format: 'yyyy-mm-dd',
    language: "pl",
    autoclose: true,
    todayHighlight: true,
    todayBtn: "linked"
}).on('changeDate', function (a) {
    
});

$('#new_memo_start_date_field .input-group.date').datepicker({
    format: 'yyyy-mm-dd',
    language: "pl",
    autoclose: true,
    todayHighlight: true,
    todayBtn: "linked"
}).on('changeDate', function (a) {
    
});

$('#new_memo_end_date_field .input-group.date').datepicker({
    format: 'yyyy-mm-dd',
    language: "pl",
    autoclose: true,
    todayHighlight: true,
    todayBtn: "linked"
}).on('changeDate', function (a) {
    
});